name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x, 1.22.x]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Hunspell dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qq libhunspell-dev hunspell-en-us

    - name: Test
      run: go test ./...
